version: '3.8'

services:
  postgres:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  server:
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.5'
          memory: 1024M

  client:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
